CREATE ROLE epok      WITH LOGIN PASSWORD 'Linus';
CREATE ROLE studentits WITH LOGIN PASSWORD 'Linus';
CREATE ROLE ladok     WITH LOGIN PASSWORD 'Linus';
CREATE ROLE canvas   WITH LOGIN PASSWORD 'Linus';