CREATE DATABASE epok     WITH TEMPLATE=template0 ENCODING 'UTF8';
CREATE DATABASE ladok    WITH TEMPLATE=template0 ENCODING 'UTF8';
CREATE DATABASE canvas   WITH TEMPLATE=template0 ENCODING 'UTF8';
CREATE DATABASE studentits WITH TEMPLATE=template0 ENCODING 'UTF8';